import required plugins
this might have worked with a hacked gnucap library, who knows. anyway,
the plugin code is being used, but not in the intended way.

after build, i still get an error, it does seem related to swig.
what is initpython?

$ PYTHONPATH=.:.libs python example/simple.py
Traceback (most recent call last):
  File "example/simple.py", line 5, in <module>
    import gnucap
  File "/home/felix/extern/gnucap-python/gnucap.py", line 17, in <module>
    _gnucap = swig_import_helper()
  File "/home/felix/extern/gnucap-python/gnucap.py", line 16, in swig_import_helper
    return importlib.import_module('python')
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: dynamic module does not define init function (initpython)