getting there
$ GNUCAP_PLUGPATH=/usr/local/lib/gnucap PYTHONPATH=.:.libs python example/simple.py
@@#
@@@:../c_attach.cc:117:do_it
Traceback (most recent call last):
  File "example/simple.py", line 8, in <module>
    gnucap.command("load gnucap-default-plugins.so")
Exception: load gnucap-default-plugins.so
     ^ ? /usr/local/lib/gnucap/gnucap-default-plugins.so: undefined symbol: CKT_BASE::help(CS&, OMSTREAM&) const

(i don't understand. gnucap.command lives in _gnucap.so. is linked
against libgnucap.so. CKT_BASE::help(CS&, OMSTREAM&) const is defined
there...)